spring:
  profiles:
    active: native
  application:
    name: HorizonSingleApplication
server:
  shutdown: graceful
  servlet:
    context-path: /single
  port: 8080
  server-header: "Horizon Single Application"