spring:
  profiles:
    active: native
  application:
    name: InfrastructureAuthorityCentralResourceApplication
server:
  shutdown: graceful
  servlet:
    context-path: /infrastructureAuthorityCentralResource
  port: 1649
  server-header: "InfrastructureAuthorityCentralResource Application"