spring:
  profiles:
    active: native
  application:
    name: HorizonUnifyAuthorityCentralResourceApplication
server:
  shutdown: graceful
  servlet:
    context-path: /horizon/authority-central-resource
  port: 1649