server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: horizon-stand-alone-${spring.profiles.active}
    url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: 'ENC(ITGKG+x43Pe+3VLn5eNs9XL1G6yLFx/rPHx/TwDwrNwi3HY1zJhDSbr/mPa/RCMPo+cteHCg2n7HLrnXDQ1VeeWKZJRcLegmOTJUt5wrbnA9x9p6FQVduCqnidxd15d68SFFeMlEdTIv36aDqZ5ApFwVYsXFiO6C3521LLM8Nq8=)'
    password: 'ENC(TVqXpEqe83s4cDr1YEA/U8gukiHKVPQA3ZbwcLCiyhhUxMx1JlwrwFZdtG+yTsKpCqf0rNrwU4dA3KkPivzCx4J8aIDpjzymfxqtXijt5K1ceGE5lyXNR66mANa6qq6LfcfVjulU1lnheNg/jjDIYlTpHotZ8VWd+thhyq91920=)'
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
