spring:
  profiles:
    active: native
  application:
    name: HorizonUnifyAuthorityCentralApplication
server:
  shutdown: graceful
  servlet:
    context-path: /horizon/authority-central
  port: 1469