<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Authority Central</title>
    <link rel="shortcut icon" href="${req.contextPath}/favicon.ico" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <!-- MacroStyleHook Start -->
    <@MacroStyleHook/>
    <!-- MacroStyleHook End -->
</head>
<body>

<!-- MacroViewHook Start -->
<@MacroViewHook/>
<!-- MacroViewHook End -->

<!-- MacroScriptHook Start -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.js"></script>
<@MacroScriptHook/>
<!-- MacroScriptHook End -->
</body>
</html>