spring:
  profiles:
    active: native
  application:
    name: InfrastructureAuthorityCentralApplication
server:
  shutdown: graceful
  servlet:
    context-path: /infrastructureAuthorityCentral
  port: 1469
  server-header: "InfrastructureAuthorityCentral Application"